# Generated by Django 4.2 on 2023-07-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media',
            field=models.FileField(upload_to='posts'),
        ),
    ]
