# Generated by Django 4.2 on 2023-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_full_name_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile-pictures/base-profile-pic.jpg', upload_to='profile-pictures/'),
        ),
    ]
