# Generated by Django 4.2 on 2023-06-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_gender_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('PreferNotToSay', 'Prefer not to say'), ('Other', 'Other')], default='1', max_length=18),
        ),
    ]
